# Generated by Django 2.2 on 2019-05-07 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('prof_id', models.AutoField(db_column='prof_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('office', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('picture', models.CharField(max_length=400)),
                ('courses', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'professor',
                'ordering': ['last_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfessorRating',
            fields=[
                ('rating_id', models.AutoField(db_column='rating_ID', primary_key=True, serialize=False)),
                ('student_email', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('prof', models.ForeignKey(db_column='prof_ID', on_delete=django.db.models.deletion.CASCADE, to='professors.Professor')),
            ],
            options={
                'db_table': 'prof_rating',
                'ordering': ['-rating_id'],
                'managed': True,
            },
        ),
    ]
