# Generated by Django 2.2 on 2019-04-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
