# Generated by Django 2.2 on 2019-04-25 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(db_column='course_ID', primary_key=True, serialize=False)),
                ('course_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=300)),
                ('credits', models.IntegerField()),
                ('prerequisites', models.CharField(max_length=100)),
                ('fulfillment', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'course_prof',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('rating_id', models.AutoField(db_column='rating_ID', primary_key=True, serialize=False)),
                ('student_email', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.CharField(max_length=300)),
                ('course', models.ForeignKey(db_column='course_ID', on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'db_table': 'course_rating',
                'managed': True,
            },
        ),
    ]
