# Generated by Django 2.2 on 2019-04-25 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserating',
            name='prof_id',
            field=models.ForeignKey(db_column='prof_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='professors.Professor'),
        ),
        migrations.AddField(
            model_name='courseprof',
            name='course',
            field=models.ForeignKey(db_column='course_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='courseprof',
            name='professor',
            field=models.ForeignKey(db_column='professor_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='professors.Professor'),
        ),
    ]
